---
lang: zh-CN
title: 语法基础
description: 页面的描述
# 
contributors: true
---

## 数据类型转换

### 强制转换

1. `Number()`

```js
// 数值：转换后还是原来的值
Number(324) // 324

// 字符串：如果可以被解析为数值，则转换为相应的数值
Number('324') // 324

// 字符串：如果不可以被解析为数值，返回 NaN
Number('324abc') // NaN

// 空字符串转为0
Number('') // 0

// 布尔值：true 转成 1，false 转成 0
Number(true) // 1
Number(false) // 0

// undefined：转成 NaN
Number(undefined) // NaN

// null：转成0
Number(null) // 0

//Number函数将字符串转为数值，要比parseInt函数严格很多。
//只要有一个字符无法转成数值，整个字符串就会被转为NaN。
parseInt('42 cats') // 42
Number('42 cats') // NaN
```

2. `String()`

```js
//原始类型值转换为字符串
String(123) // "123"
String('abc') // "abc"
String(true) // "true"
String(undefined) // "undefined"
String(null) // "null"

//对象类型值转换为字符串
String({a: 1}) // "[object Object]"
String([1, 2, 3]) // "1,2,3"
```
3. `Boolean()`

```js
Boolean(undefined) // false
Boolean(null) // false
Boolean(0) // false
Boolean(NaN) // false
Boolean('') // false

Boolean({}) // true
Boolean([]) // true
Boolean(new Boolean(false)) // true

Boolean(' ') // true // 注意字符串内有个空格
```

### 自动转换

以下三种情况时，JavaScript 会自动转换数据类型:

1. 第一种情况，不同类型的数据互相运算。

```js
123 + 'abc' // "123abc"
```

2. 第二种情况，对非布尔值类型的数据求布尔值。

```js
if('abc'){
    console.log('hello')
}
```

3. 第三种情况，对非数值类型的值使用一元运算符（即`+`和`-`）。

```js
+ {foo: 'bar'} // NaN
- [1, 2, 3] // NaN
```

自动转换为布尔值 

`JavaScript `遇到预期为布尔值的地方（比如`if`语句的条件部分），系统内部会自动调用Boolean()函数。

除了以下五个值，其他都是自动转为true。

- `undefined`
- `null`
- `+0`或`-0`
- `NaN`
- `''`（空字符串）

```js
if ( !undefined
  && !null
  && !0
  && !NaN
  && !''
) {
  console.log('true');
} // true
```

自动转换为字符串

JavaScript 遇到预期为字符串的地方,具体规则是，先将复合类型的值转为原始类型的值，再将原始类型的值转为字符串。

```js
'5' + 1 // '51'
'5' + true // "5true"
'5' + false // "5false"
'5' + {} // "5[object Object]"
'5' + [] // "5"
'5' + function (){} // "5function (){}"
'5' + undefined // "5undefined"
'5' + null // "5null"

//这种自动转换很容易出错。
var obj = {
  width: '100'
};

obj.width + 20 // "10020"
//可能期望返回120，但是由于自动转换，实际上返回了一个字符10020。
```
自动转换为数值 

`JavaScript` 遇到预期为数值的地方,系统内部会自动调用`Number()`函数。

```js
'5' - '2' // 3
'5' * '2' // 10
true - 1  // 0
false - 1 // -1
'1' - 1   // 0
'5' * []    // 0
false / '5' // 0
'abc' - 1   // NaN
null + 1 // 1
undefined + 1 // NaN

//一元运算符也会把运算子转成数值。
+'abc' // NaN
-'abc' // NaN
+true // 1
-false // 0
```

::: warning 注意
`null`转为数值时为`0`，而`undefined`转为数值时为`NaN`。
:::

## 错误处理机制

### Error 实例对象

`JavaScript` 原生提供`Error`构造函数，所有抛出的错误都是这个构造函数的实例。

```js
var err = new Error('出错了');
err.message // "出错了"
//抛出Error实例对象以后，整个程序就中断在发生错误的地方，不再往下执行。
```

大多数 `JavaScript` 引擎，对`Error`实例还提供`name`和`stack`属性，分别表示错误的名称和错误的堆栈，但它们是非标准的，不是每种实现都有。

- `message`：错误提示信息
- `name`：错误名称（非标准属性）
- `stack`：错误的堆栈（非标准属性）

```js
//使用name和message这两个属性，可以对发生什么错误有一个大概的了解。
if (error.name) {
  console.log(error.name + ': ' + error.message);
}

/*------------------------------------------------------------*/

//stack属性用来查看错误发生时的堆栈。
function throwit() {
  throw new Error('');
}

function catchit() {
  try {
    throwit();
  } catch(e) {
    console.log(e.stack); // print stack trace
  }
}

catchit()
// Error
//    at throwit (~/examples/throwcatch.js:9:11)
//    at catchit (~/examples/throwcatch.js:3:9)
//    at repl:1:5
```

### 原生错误类型

`JavaScript` 还定义了其他6种错误对象。也就是说，存在`Error`的6个派生对象。

1. `SyntaxError`对象是解析代码时发生的语法错误。

```js
// 变量名错误
var 1a;
// Uncaught SyntaxError: Invalid or unexpected token

// 缺少括号
console.log 'hello');
// Uncaught SyntaxError: Unexpected string
```

2. `ReferenceError`对象是引用一个不存在的变量时发生的错误。

```js
// 使用一个不存在的变量
unknownVariable
// Uncaught ReferenceError: unknownVariable is not defined

//另一种触发场景是，将一个值分配给无法分配的对象，比如对函数的运行结果赋值。
// 等号左侧不是变量
console.log() = 1
// Uncaught ReferenceError: Invalid left-hand side in assignment
```

3. `RangeError`对象是一个值超出有效范围时发生的错误。主要有几种情况，一是数组长度为负数，二是Number对象的方法参数超出范围，以及函数堆栈超过最大值。

```js
// 数组长度不得为负数
new Array(-1)
// Uncaught RangeError: Invalid array length
```

4. `TypeError`对象 

```js
new 123
// Uncaught TypeError: 123 is not a constructor

var obj = {};
obj.unknownMethod()
// Uncaught TypeError: obj.unknownMethod is not a function
```

5. `URIError`对象是 `URI` 相关函数的参数不正确时抛出的错误，主要涉及`encodeURI()`、`decodeURI()`、`encodeURIComponent()`、`decodeURIComponent()`、`escape()`和`unescape()`这六个函数。

```js
decodeURI('%2')
// URIError: URI malformed
```

6. `eval`函数没有被正确执行时，会抛出`EvalError`错误。该错误类型已经不再使用了，只是为了保证与以前代码兼容，才继续保留。

7. 以上这6种派生错误，连同原始的`Error`对象，都是构造函数。开发者可以使用它们，手动生成错误对象的实例。这些构造函数都接受一个参数，代表错误提示信息（`message`）。

```js
var err1 = new Error('出错了！');
var err2 = new RangeError('出错了，变量超出有效范围！');
var err3 = new TypeError('出错了，变量类型无效！');

err1.message // "出错了！"
err2.message // "出错了，变量超出有效范围！"
err3.message // "出错了，变量类型无效！"
```

### 自定义错误

下面代码自定义一个错误对象`UserError`，让它继承`Error`对象。然后，就可以生成这种自定义类型的错误了。

```js
function UserError(message) {
  this.message = message || '默认信息';
  this.name = 'UserError';
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError;

new UserError('这是自定义的错误！');
```

### throw语句

`throw`语句的作用是手动中断程序执行，抛出一个错误。

```js
var x = -1;

if (x <= 0) {
  throw new Error('x 必须为正数');
}
// Uncaught Error: x 必须为正数
// 可以看到，throw抛出的错误就是它的参数，这里是一个Error对象的实例。
```
`throw`也可以抛出自定义错误。而且`throw`可以抛出任何类型的值。
```js
function UserError(message) {
  this.message = message || '默认信息';
  this.name = 'UserError';
}

throw new UserError('出错了！');
// Uncaught UserError {message: "出错了！", name: "UserError"}
```
上面代码中，`throw`抛出的是一个UserError实例。

### try...catch 结构

`JavaScript` 提供了`try...catch`结构，允许对错误进行处理，选择是否往下执行。

```js
try {
  throw new Error('出错了!');
} catch (e) {
  console.log(e.name + ": " + e.message);
  console.log(e.stack);
}
// Error: 出错了!
//   at <anonymous>:3:9
//   ...
```

`catch`代码块捕获错误之后，程序不会中断，会按照正常流程继续执行下去。`try...catch`可以互相嵌套。

```js
try {
  throw "出错了";
} catch (e) {
  console.log(111);
}
console.log(222);
// 111
// 222
```

### finally 代码块

`try...catch`结构允许在最后添加一个`finally`代码块，表示不管是否出现错误，都必需在最后运行的语句。

```js
function cleansUp() {
  try {
    throw new Error('出错了……');
    console.log('此行不会执行');
  } finally {
    console.log('完成清理工作');
  }
}

cleansUp()
// 完成清理工作
// Uncaught Error: 出错了……
//    at cleansUp (<anonymous>:3:11)
//    at <anonymous>:10:1
```

上面代码中，由于没有`catch`语句块，一旦发生错误，代码就会中断执行。中断执行之前，会先执行`finally`代码块，然后再向用户提示报错信息。

```js
function idle(x) {
  try {
    console.log(x);
    return 'result';
  } finally {
    console.log('FINALLY');
  }
}

idle('hello')
// hello
// FINALLY
```

上面代码中，`try`代码块没有发生错误，而且里面还包括`return`语句，但是`finally`代码块依然会执行。而且，这个函数的返回值还是`result`。

下面的例子说明，`return`语句的执行是排在`finally`代码之前，只是等`finally`代码执行完毕后才返回。

```js
var count = 0;
function countUp() {
  try {
    return count;
  } finally {
    count++;
  }
}

countUp()
// 0
count
// 1
```

下面的例子充分反映了`try...catch...finally`这三者之间的执行顺序。

```js
function f() {
  try {
    console.log(0);
    throw 'bug';
  } catch(e) {
    console.log(1);
    return true; // 这句原本会延迟到 finally 代码块结束再执行
    console.log(2); // 不会运行
  } finally {
    console.log(3);
    return false; // 这句会覆盖掉前面那句 return
    console.log(4); // 不会运行
  }

  console.log(5); // 不会运行
}

var result = f();
// 0
// 1
// 3

result
// false
```

上面代码中，`catch`代码块结束执行之前，会先执行`finally`代码块。

`catch`代码块之中，触发转入`finally`代码块的标志，不仅有`return`语句，还有`throw`语句。

```js
function f() {
  try {
    throw '出错了！';
  } catch(e) {
    console.log('捕捉到内部错误');
    throw e; // 这句原本会等到finally结束再执行
  } finally {
    return false; // 直接返回
  }
}

try {
  f();
} catch(e) {
  // 此处不会执行
  console.log('caught outer "bogus"');
}

//  捕捉到内部错误
```

上面代码中，进入`catch`代码块之后，一遇到`throw`语句，就会去执行`finally`代码块，其中有`return false`语句，因此就直接返回了，不再会回去执行`catch`代码块剩下的部分了。


## console 对象与控制台

`console`的常见用途有两个。

- 调试程序，显示网页代码运行时的错误信息。
- 提供了一个命令行接口，用来与网页代码互动。

### console 对象的静态方法

`console`对象的所有方法，都可以被覆盖。因此，可以按照自己的需要，定义`console.log`方法。

```js
['log', 'info', 'warn', 'error'].forEach(function(method) {
  console[method] = console[method].bind(
    console,
    new Date().toISOString()
  );
});

console.log("出错了！");
// 2014-05-18T09:00.000Z 出错了！
```

1. `console.log()`:方法用于在控制台输出信息。
2. `console.info()`:是`console.log`方法的别名，用法完全一样。只不过`console.info`方法会在输出信息的前面，加上一个蓝色图标。
3. `console.debug()`:输出的信息不会显示,与`console.log`方法类似，只有在打开显示级别在`verbose`的情况下，才会显示。
4. `console.warn()`，`console.error()`

可以这样理解，`log`方法是写入标准输出（`stdout`），`warn`方法和`error`方法是写入标准错误（stderr）。

```js
console.error('Error: %s (%i)', 'Server is not responding', 500)
// Error: Server is not responding (500)
console.warn('Warning! Too few nodes (%d)', document.childNodes.length)
// Warning! Too few nodes (1)
```

5. `console.table()`

```js
var languages = [
  { name: "JavaScript", fileExtension: ".js" },
  { name: "TypeScript", fileExtension: ".ts" },
  { name: "CoffeeScript", fileExtension: ".coffee" }
];

console.table(languages);
```
上面代码的`language`变量，转为表格显示如下。

|(index) | name | fileExtension|
| ------------- |:-------------:| -----:|
|0|"JavaScript"|".js"|
|1|"TypeScript"|".ts"|
|2|"CoffeeScript"|".coffee"|

6. `console.count() `

```js
//count方法用于计数，输出它被调用了多少次。
function greet(user) {
  console.count();
  return 'hi ' + user;
}

greet('bob')
//  : 1
// "hi bob"

greet('alice')
//  : 2
// "hi alice"

greet('bob')
//  : 3
// "hi bob"
```

7. `console.dir()`，`console.dirxml()`

`dir`方法用来对一个对象进行检查（`inspect`），并以易于阅读和打印的格式显示。

```js
console.log({f1: 'foo', f2: 'bar'})
// Object {f1: "foo", f2: "bar"}

console.dir({f1: 'foo', f2: 'bar'})
// Object
//   f1: "foo"
//   f2: "bar"
//   __proto__: Object
```

`dirxml`方法主要用于以目录树的形式，显示` DOM `节点。

```js
console.dirxml(document.body)
```

如果参数不是 `DOM` 节点，而是普通的 `JavaScript` 对象，`console.dirxml`等同于`console.dir`。

8. `onsole.assert()`

`console.assert`方法主要用于程序运行过程中，进行条件判断，如果不满足条件，就显示一个错误，但不会中断程序执行。这样就相当于提示用户，内部状态不正确。

它接受两个参数，第一个参数是表达式，第二个参数是字符串。只有当第一个参数为`false`，才会提示有错误，在控制台输出第二个参数，否则不会有任何结果。

```js
console.assert(false, '判断条件不成立')
// Assertion failed: 判断条件不成立

// 相当于
try {
  if (!false) {
    throw new Error('判断条件不成立');
  }
} catch(e) {
  console.error(e);
}
```

9. `console.time()`，`console.timeEnd()`

这两个方法用于计时，可以算出一个操作所花费的准确时间。比较常用。

```js
console.time('Array initialize');

var array= new Array(1000000);
for (var i = array.length - 1; i >= 0; i--) {
  array[i] = new Object();
};

console.timeEnd('Array initialize');
// Array initialize: 1914.481ms
```

10. `console.group()`，`console.groupEnd()`，`console.groupCollapsed()`

`console.group`和`console.groupEnd`这两个方法用于将显示的信息分组。它只在输出大量信息时有用，分在一组的信息，可以用鼠标折叠/展开。

```js
console.group('一级分组');
console.log('一级分组的内容');

console.group('二级分组');
console.log('二级分组的内容');

console.groupEnd(); // 二级分组结束
console.groupEnd(); // 一级分组结束
```

`console.groupCollapsed`方法与`console.group`方法很类似

11. `console.trace()`，`console.clear() `

`console.trace`方法显示当前执行的代码在堆栈中的调用路径。

```js
console.trace()
// console.trace()
//   (anonymous function)
//   InjectedScript._evaluateOn
//   InjectedScript._evaluateAndWrap
//   InjectedScript.evaluate
```
`console.clear`方法用于清除当前控制台的所有输出，将光标回置到第一行。如果用户选中了控制台的`“Preserve log”`选项，`console.clear`方法将不起作用。

### 控制台命令行 API

浏览器控制台中，除了使用`console`对象，还可以使用一些控制台自带的命令行方法。

### debugger 语句

`debugger`语句主要用于除错，作用是设置断点。如果有正在运行的除错工具，程序运行到`debugger`语句时会自动停下。如果没有除错工具，`debugger`语句不会产生任何结果，` JavaScript `引擎自动跳过这一句。